backend:
  name: github
  repo: rianarianto/yotek-web
  branch: main
# local_backend: true # Uncomment this to test locally using 'npx decap-server'

media_folder: "public/images" 
public_folder: "/images"

collections:
  - name: "news"
    label: "Berita Yotek"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "Kategori", name: "category", widget: "string", default: "Company" }
      - { label: "Deskripsi Singkat", name: "description", widget: "text" }
      - { label: "Gambar Thumbnail (Link atau Upload)", name: "image", widget: "image", required: false }
      - { label: "Isi Berita Lengkap", name: "body", widget: "markdown" }

  - name: "career"
    label: "Lowongan Pekerjaan"
    folder: "src/content/career"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Posisi Pekerjaan", name: "position", widget: "string" }
      - { label: "Tipe Pekerjaan", name: "type", widget: "select", options: ["Full-time", "Part-time", "Contract", "Internship"] }
      - { label: "Lokasi Penempatan", name: "location", widget: "string", default: "Pekanbaru, Indonesia" }
      - { label: "Tanggal Buka", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "Tanggal Tutup", name: "closeDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD", required: false }
      - { label: "Deskripsi Pekerjaan", name: "description", widget: "text" }
      - { label: "Syarat & Kualifikasi", name: "requirements", widget: "list", field: {label: "Syarat", name: "requirement", widget: "string"} }
      - { label: "Detail Lainnya", name: "body", widget: "markdown" }
